name: Deploy to GitHub Pages v2

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Debug build output
        run: ls -la dist  # Verifica che la cartella dist sia presente

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Nome dell'artifact
          path: dist          # La cartella di output generata dalla build

      - name: List uploaded artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(artifacts.data);  // Mostra gli artifact caricati

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4