name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '7.1.0'

      - name: Install dependencies and build the site
        run: |
          pnpm install
          pnpm build

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: dist  # La cartella generata dalla build (dove sono i file statici)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Questo token è usato per autenticarsi su GitHub

      - name: Output URL
        run: echo "Site deployed to https://yourusername.github.io/yourrepository"